### ISSUE TITLE
Simple Roadmap

### ISSUE THREAD

**Issue by roni-estein** [tinywinddev/tinywind#3]
If you list the upcoming components in a road map you won't have duplicated requests. Also I won't build those myself :)

**Comment by ryangjchandler** [comment]
The issues themselves will serve as a roadmap, so when I'm thinking of creating a new component, I'll create an issue for it. :)

**Comment by roni-estein** [comment]
Component re-use
A charming endeavour for all
You are very clever


And yes, I just complimented your strategy in Haiku
